version: '3'

volumes:
  php-senior-test-database:
    external: true

networks:
  php-senior-test-network:
    external: true

services:
  php-senior-test:
    image: ambientum/php:7.4-nginx
    container_name: php-senior-test
    volumes:
      - .:/var/www/app
    ports:
      - "8000:8080"
    networks:
      - php-senior-test-network

  php-senior-test-database:
    image: mysql:5.7
    volumes:
      - php-senior-test-database:/var/lib/mysql
    ports:
      - "33060:3306"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
      - "MYSQL_DATABASE=database"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=secret"
    networks:
      - php-senior-test-network
